# first makefile under AntColonyOptimization folder will be run like make clean && make run

run:
	cd AntColonyOptimization && make clean && make run
	source venv/bin/activate && cd map_draw && python3 rota_cizim.py